### ISSUE TITLE
Error 'import pysinsy' when using nnsvs

### ISSUE THREAD

**Issue by Aniana0** [oatsu-gh/setup-nnsvs-on-wsl#2]
My English is bad. So I used a translator. I'm sorry.

I installed wsl1 and Ubuntu to use nnsvs.
Then I tried to install nnsvs using setup-nsvs-on-wsl, but it didn't install properly because of an error.
There was an error installing sinsy:
`CMake Error at CMakeLists.txt:20 (add_subdirectory):
add_subdirectory given source "lib/hts_engine_API/hts_engine/src" which is not an existing directory.`
So I copied the ~/hts_engine_API/src folder to ~/siny/src/lib/hts_engine_API/hts_engine/ and restarted the install.
nnsvs were installed but did not work.
I found an error when 'import pysinsy':
.>>> import pysinsy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pysinsy/__init__.py", line 5, in <module>
    from .sinsy import Sinsy
ImportError: /usr/local/lib/libsinsy.so.0.9: undefined symbol: HTS_Engine_get_nsamples

First, I asked the producer of pysinsy(https://github.com/r9y9/pysinsy/issues/5), and he answered to ask here.
Please help me to resolve this error...😢
Thank you for reading!

**Original Message(Korean):**
저는 nnsvs를 사용하기 위해 wsl1과 Ubuntu를 설치했습니다.
그 다음 setup-nsvs-on-wsl를 이용해 nnsvs를 설치하려고 했지만, 오류가 나서 설치가 되지 않았습니다.
sinsy를 설치할 때 오류가 있었습니다:
`CMake Error at CMakeLists.txt:20 (add_subdirectory):
add_subdirectory given source "lib/hts_engine_API/hts_engine/src" which is not an existing directory.`
그래서 저는 ~/hts_engine_API/src 폴더를 ~/siny/src/lib/hts_engine_API/hts_engine/에 복사한 뒤 설치를 다시 시작했습니다.
nnsvs는 설치되었지만 작동하지 않았습니다.
저는 'import pysinsy'에서 오류를 찾았습니다:
.>>> import pysinsy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pysinsy/__init__.py", line 5, in <module>
    from .sinsy import Sinsy
ImportError: /usr/local/lib/libsinsy.so.0.9: undefined symbol: HTS_Engine_get_nsamples

먼저 저는 pysinsy의 제작자에게 문의했고(https://github.com/r9y9/pysinsy/issues/5), 이곳에도 문의해보라는 답변을 받았습니다.
제가 이 오류를 해결할 수 있도록 도와주세요...😢
읽어주셔서 감사합니다.

**Comment by oatsu-gh** [comment]
Sorry for the much late.

The issue sould be solved by command reffered at "困ったときは" section.
https://github.com/oatsu-gh/setup-nnsvs-on-wsl/blob/master/README.md

Run `export LD_LIBRARY_PATH=/usr/local/lib` at the directory where the error occured.

**Comment by Aniana0** [comment]
Thank you for your answer!
I had already run it when I installed nnsvs in July. But there was the same error.
I am sorry for missing an explanation about this...😅
After receiving the answer, there was still an error even after running `export LD_LIBRARY_PATH=/usr/local/lib` and reinstalling nnsvs.
But when I deleted everything and installed it again, the error disappeared.
I had no idea why there was an error in July.
Because I installed nnsvs in the same process as July...
I'm so sorry to make you spend your time...
Thank you for your help.

**Original Message(Korean):**
답변해주셔서 감사합니다!
저는 이미 그것을 7월에 nnsvs를 설치할 때 시도해보았습니다. 하지만 같은 오류가 발생했습니다.
이것에 대한 설명을 누락해서 죄송합니다...
저는 답변을 받은 이후에 `export LD_LIBRARY_PATH=/usr/local/lib`를 실행하고 nnsvs를 다시 설치해보았지만 여전히 같은 오류가 났습니다.
그런데 모든 것을 삭제 한 뒤, 모든 것을 다시 다운 받고 nnsvs를 설치하니 오류가 사라졌습니다.
7월에 설치한 과정을 그대로 재현했음에도 오류가 사라졌기 때문에, 대체 왜 오류가 사라졌는지 알 수 없었습니다.
도움을 주셨는데 허무하게 해결돼버려서 정말 죄송합니다...
도와주셔서 감사합니다!
